import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/v1/');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await expect(page.getByText('Products')).toBeVisible();
  await page.locator('#header_container div').first().click();
  await page.getByRole('combobox').selectOption('za');
  await page.getByRole('combobox').selectOption('lohi');
  await page.getByRole('combobox').selectOption('hilo');
  await page.locator('#shopping_cart_container').getByRole('link').click();
  await page.locator('#header_container div').nth(1).click();
  await page.getByText('Your Cart').click();
  await page.getByText('QTY').click();
  await page.getByText('QTYDESCRIPTION').click();
  await page.getByRole('link', { name: 'Continue Shopping' }).click();
  await page.locator('.peek').click();
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.getByRole('link', { name: 'About' }).click();
  await page.goto('https://www.saucedemo.com/v1/inventory.html');
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.getByRole('link', { name: 'All Items' }).click();
  await page.locator('#shopping_cart_container').getByRole('link').click();
  await page.getByRole('link', { name: 'CHECKOUT' }).click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="postalCode"]').click();
  await page.getByRole('link', { name: 'CANCEL' }).click();
  await page.getByRole('link', { name: 'CHECKOUT' }).click();
  await page.getByRole('button', { name: 'CONTINUE' }).click();
  await page.locator('[data-test="error"]').click();
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.getByText('Reset App State').click();
  await page.getByRole('button', { name: 'Close Menu' }).click();
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.getByRole('link', { name: 'All Items' }).click();
  await page.getByText('© 2020 Sauce Labs. All Rights').click();
  await page.getByText('LinkedIn').click();
  await page.getByText('Facebook').click();
  await page.getByText('Twitter').click();
  await page.getByRole('contentinfo').getByRole('img').click();
  await page.locator('#item_0_img_link').getByRole('img').click();
  await page.getByText('$').click();
  await page.getByText('A red light isn\'t the desired').click();
  await page.getByText('Sauce Labs Bike LightA red').click();
  await page.getByRole('img').click();
  await page.getByRole('button', { name: 'ADD TO CART' }).click();
  await page.getByRole('button', { name: 'REMOVE' }).click();
  await page.getByRole('button', { name: '<- Back' }).click();
  await page.locator('#item_4_img_link').getByRole('img').click();
  await page.getByRole('button', { name: '<- Back' }).click();
});